package srd

import (
	"context"
	"encoding/json"
	"fmt"
	"time"
)

// Adapter normalizes output from a specific external security tool into ExternalAssessmentReport.
type Adapter interface {
	ToolID() string
	ToolName() string
	IsEnabled(cfg Config) bool
	Parse(ctx context.Context, input []byte) (*ExternalAssessmentReport, error)
	SupportsFormat(path string) bool
}

var registeredAdapters = make(map[string]Adapter)

// Register adds an adapter to the global registry.
func Register(ad Adapter) {
	registeredAdapters[ad.ToolID()] = ad
}

// List returns all registered adapters.
func List() []Adapter {
	out := make([]Adapter, 0, len(registeredAdapters))
	for _, a := range registeredAdapters {
		out = append(out, a)
	}
	return out
}

// Get returns the adapter for the given tool ID.
func Get(toolID string) (Adapter, bool) {
	a, ok := registeredAdapters[toolID]
	return a, ok
}

// GenericJSONReport is the expected JSON structure for the GenericAdapter.
// Can be generated by any tool that conforms to this minimal schema.
type GenericJSONReport struct {
	Tool     string          `json:"tool"`
	HostID   string          `json:"host_id"`
	Hostname string          `json:"hostname"`
	ScanTime string          `json:"scan_time"`
	Score    json.RawMessage `json:"score,omitempty"`
	Grade    string          `json:"grade,omitempty"`
	Items    json.RawMessage `json:"items"`
	Metadata map[string]string `json:"metadata,omitempty"`
}

// GenericCheckItem is a single item in GenericJSONReport.Items.
type GenericCheckItem struct {
	ID          string            `json:"id"`
	RuleID     string            `json:"rule_id,omitempty"`
	Title      string            `json:"title"`
	Description string            `json:"description,omitempty"`
	Severity   string            `json:"severity"`
	Result     string            `json:"result"`
	Category   string            `json:"category"`
	FailAt     int64             `json:"fail_at_unix,omitempty"`
	Refs       []string          `json:"refs,omitempty"`
}

// BuildReportFromGeneric constructs an ExternalAssessmentReport from GenericJSONReport.
func BuildReportFromGeneric(raw GenericJSONReport, profile SeverityProfile) (*ExternalAssessmentReport, error) {
	scanTime := time.Now()
	if raw.ScanTime != "" {
		if t, err := time.Parse(time.RFC3339, raw.ScanTime); err == nil {
			scanTime = t
		}
	}

	var items []GenericCheckItem
	if raw.Items != nil {
		if err := json.Unmarshal(raw.Items, &items); err != nil {
			return nil, fmt.Errorf("parse items: %w", err)
		}
	}

	report := &ExternalAssessmentReport{
		Tool:     raw.Tool,
		HostID:   raw.HostID,
		Hostname: raw.Hostname,
		ScanTime: scanTime,
		RawGrade: raw.Grade,
		Items:    make([]ExternalCheckResult, 0),
		Metadata: raw.Metadata,
	}

	for _, item := range items {
		result := "pass"
		if item.Result == "fail" || item.Result == "error" || item.Result == "warning" {
			result = "fail"
		}

		failAt := item.FailAt
		if failAt == 0 {
			failAt = scanTime.Unix()
		}

		delta := 0.0
		if result == "fail" {
			delta = profile.DeltaFromSeverity(item.Severity)
		}

		report.Items = append(report.Items, ExternalCheckResult{
			CheckID:     item.ID,
			RuleID:     item.RuleID,
			Title:       item.Title,
			Description: item.Description,
			Severity:    item.Severity,
			Result:      result,
			Delta:       delta,
			FailAt:      failAt,
			Category:    item.Category,
			Refs:        item.Refs,
		})
	}

	return report, nil
}
