frr version 10.1
frr defaults traditional
hostname r5
log file /etc/frr/frr.log
!
interface eth1
 ip address 10.10.200.14/30
!
interface eth2
 ip address 10.10.7.1/24
!
interface eth3
 ip address 10.10.8.1/24
!
interface eth4
 ip address 10.10.200.26/30
!
interface eth5
 ip address 10.10.200.29/30
!
interface eth6
 ip address 10.10.12.1/24
!
router ospf
 ospf router-id 5.5.5.5
 network 10.10.200.12/30 area 0
 network 10.10.7.0/24 area 0
 network 10.10.8.0/24 area 0
 network 10.10.200.24/30 area 0
 network 10.10.200.28/30 area 0
 network 10.10.12.0/24 area 0
!
line vty
