frr version 10.1
frr defaults traditional
hostname r2
log file /etc/frr/frr.log
!
interface eth1
 ip address 10.10.200.2/30
!
interface eth2
 ip address 10.10.1.1/24
!
interface eth3
 ip address 10.10.2.1/24
!
interface eth4
 ip address 10.10.200.17/30
!
interface eth5
 ip address 10.10.200.30/30
!
interface eth6
 ip address 10.10.9.1/24
!
router ospf
 ospf router-id 2.2.2.2
 network 10.10.200.0/30 area 0
 network 10.10.1.0/24 area 0
 network 10.10.2.0/24 area 0
 network 10.10.200.16/30 area 0
 network 10.10.200.28/30 area 0
 network 10.10.9.0/24 area 0
!
line vty
