frr version 10.1
frr defaults traditional
hostname r3
log file /etc/frr/frr.log
!
interface eth1
 ip address 10.10.200.6/30
!
interface eth2
 ip address 10.10.3.1/24
!
interface eth3
 ip address 10.10.4.1/24
!
interface eth4
 ip address 10.10.200.18/30
!
interface eth5
 ip address 10.10.200.21/30
!
interface eth6
 ip address 10.10.10.1/24
!
router ospf
 ospf router-id 3.3.3.3
 network 10.10.200.4/30 area 0
 network 10.10.3.0/24 area 0
 network 10.10.4.0/24 area 0
 network 10.10.200.16/30 area 0
 network 10.10.200.20/30 area 0
 network 10.10.10.0/24 area 0
!
line vty
