frr version 10.1
frr defaults traditional
hostname r4
log file /etc/frr/frr.log
!
interface eth1
 ip address 10.10.200.10/30
!
interface eth2
 ip address 10.10.5.1/24
!
interface eth3
 ip address 10.10.6.1/24
!
interface eth4
 ip address 10.10.200.22/30
!
interface eth5
 ip address 10.10.200.25/30
!
interface eth6
 ip address 10.10.11.1/24
!
router ospf
 ospf router-id 4.4.4.4
 network 10.10.200.8/30 area 0
 network 10.10.5.0/24 area 0
 network 10.10.6.0/24 area 0
 network 10.10.200.20/30 area 0
 network 10.10.200.24/30 area 0
 network 10.10.11.0/24 area 0
!
line vty
