#!/bin/bash
echo "========== T5 证据: 心跳超时与恢复 =========="
echo "-- agent timed out 记录 (host1) --"
docker exec asc-asscor-edge0 bash -c "grep -E 'agent timed out' /var/log/asscor-kernel.log | tail -2"
echo "-- host1 重新注册 --"
docker exec asc-asscor-edge0 bash -c "grep 'identity: agent registered' /var/log/asscor-kernel.log | grep host1 | tail -1"
echo "-- identity 绑定保留 --"
docker exec asc-asscor-edge0 bash -c "grep -o '\"host1\":\"[a-f0-9]*' /var/lib/asscor/heartbeat_identity.json"
echo ""
echo "========== T8 证据: r1 单点失效 =========="
echo "-- r1 停止期间心跳中断 (找最老/最新的心跳间隔) --"
docker exec asc-asscor-edge0 bash -c "grep 'heartbeat received' /var/log/asscor-kernel.log | grep -oE '\"time\":\"[^\"]+' | tail -8"
echo "-- kernel 日志中的连接/重连错误 --"
docker exec asc-asscor-edge0 bash -c "grep -E 'register|reconnect|EOF|broken pipe' /var/log/asscor-kernel.log | tail -4"
echo "-- 恢复后 agent 重注册 --"
docker exec asc-asscor-edge0 bash -c "grep 'identity: agent registered' /var/log/asscor-kernel.log | tail -2"