//go:build engine

package srd

import (
	"bytes"
	"context"
	"encoding/xml"
	"fmt"
	"strings"
	"time"
)

// OpenSCAP parses XCCDF 1.2 and OVAL 5.11 result files produced by oscap.
// Supported inputs: xccdf-results.xml (oscap xccdf eval --results),
//                   oval-results.xml (oscap oval eval --results).
//
// OpenSCAP severity-to-delta mapping (CIS/DISA STIG convention):
//   critical / cat I   -> -15
//   high      / cat II  -> -10
//   medium    / cat III -> -7.5
//   low       / cat IV  -> -5
//   info      / not applicable -> 0

type openscapAdapter struct{}

func newOpenSCAPAdapter() Adapter { return &openscapAdapter{} }

// --- XCCDF 1.2 types ---

type xccdfResults struct {
	XMLName    xml.Name        `xml:"xccdf:results"`
	TestResult xccdfTestResult `xml:"xccdf:TestResult"`
}

type xccdfTestResult struct {
	StartTime  string         `xml:"start-time,attr"`
	EndTime    string         `xml:"end-time,attr"`
	HostName   string         `xml:"target,attr"`
	Benchmark  string         `xml:"benchmark,attr"`
	RuleResult []xccdfRuleResult `xml:"xccdf:rule-result"`
}

type xccdfRuleResult struct {
	ID        string `xml:"idref,attr"`
	Time      string `xml:"time,attr"`
	Version   string `xml:"version,attr,omitempty"`
	Result    string `xml:"xccdf:result"`
	ScoreHigh float64 `xml:"xccdf:score,omitempty"`
	Messages  []xccdfMessage `xml:"xccdf:message,omitempty"`
	Metadata  []xccdfMetadata `xml:"xccdf:metadata,omitempty"`
}

type xccdfMessage struct {
	Text   string `xml:",chardata"`
	Level  string `xml:"level,attr,omitempty"`
}

type xccdfMetadata struct {
	Severity string `xml:"severity,attr,omitempty"`
	Ref      string `xml:"ref,omitempty"`
}

// --- OVAL 5.11 types ---

type ovalResults struct {
	XMLName    xml.Name        `xml:"oval-res:oval_results"`
	Generator  ovalGenerator  `xml:"generator"`
	TestResult ovalTestResult `xml:"results>test_result"`
}

type ovalGenerator struct {
	ProductName string `xml:"product_name"`
	Version     string `xml:"version"`
}

type ovalTestResult struct {
	Generator    ovalGenerator    `xml:"generator"`
	TestedConfigs []ovalTestRef   `xml:"tested_item>tested_config"`
	Definitions   []ovalDefResult `xml:"results>definition"`
}

type ovalTestRef struct {
	ObjID  string `xml:"object_id,attr"`
	VarRef string `xml:"variable_id,attr,omitempty"`
}

type ovalDefResult struct {
	ID       string            `xml:"id,attr"`
	Result   string            `xml:"result"`
	Criteria []ovalCritResult  `xml:"criteria>criterion"`
}

type ovalCritResult struct {
	Comment string `xml:"comment,attr"`
	Result  string `xml:"result,attr"`
}

// --- Adapter implementation ---

func (a *openscapAdapter) ToolID()     string { return "openscap" }
func (a *openscapAdapter) ToolName()   string { return "OpenSCAP (XCCDF/OVAL)" }
func (a *openscapAdapter) IsEnabled(cfg Config) bool {
	if enabled, ok := cfg.EnabledAdapters["openscap"]; ok {
		return enabled
	}
	return false
}

func (a *openscapAdapter) SupportsFormat(path string) bool {
	return strings.HasSuffix(path, "xccdf-results.xml") ||
		strings.HasSuffix(path, "oval-results.xml") ||
		strings.Contains(path, "oscap")
}

func (a *openscapAdapter) Parse(ctx context.Context, input []byte) (*ExternalAssessmentReport, error) {
	if bytes.HasPrefix(input, []byte("<?xml")) || bytes.HasPrefix(input, []byte("<")) {
		return a.parseXML(input)
	}
	return nil, fmt.Errorf("openscap: unrecognized input format")
}

func (a *openscapAdapter) parseXML(input []byte) (*ExternalAssessmentReport, error) {
	input = bytes.TrimSpace(input)

	// Try XCCDF first.
	if bytes.Contains(input, []byte("xccdf:results")) || bytes.Contains(input, []byte("TestResult")) {
		return a.parseXCCDF(input)
	}

	// Try OVAL.
	if bytes.Contains(input, []byte("oval-res:oval_results")) || bytes.Contains(input, []byte("oval_results")) {
		return a.parseOVAL(input)
	}

	return nil, fmt.Errorf("openscap: unrecognized XML namespace")
}

// parseXCCDF parses XCCDF 1.2 results generated by `oscap xccdf eval --results FILE`.
func (a *openscapAdapter) parseXCCDF(input []byte) (*ExternalAssessmentReport, error) {
	var results xccdfResults
	if err := xml.Unmarshal(input, &results); err != nil {
		return nil, fmt.Errorf("openscap XCCDF parse error: %w", err)
	}

	tr := results.TestResult
	scanTime := time.Now()
	if tr.StartTime != "" {
		if t, err := time.Parse(time.RFC3339, tr.StartTime); err == nil {
			scanTime = t
		}
	}

	report := &ExternalAssessmentReport{
		Tool:     "openscap",
		HostID:   tr.HostName,
		Hostname: tr.HostName,
		ScanTime: scanTime,
		Items:    make([]ExternalCheckResult, 0),
		Metadata: map[string]string{
			"benchmark": tr.Benchmark,
		},
	}

	var totalScore, count float64
	for _, rr := range tr.RuleResult {
		severity := "unknown"
		for _, m := range rr.Messages {
			if m.Level == "info" || m.Level == "warning" || m.Level == "error" || m.Level == "fatal" {
				severity = mapOpenSCAPSeverity(m.Level)
				break
			}
		}

		result := normalizeXCCDFResult(rr.Result)
		delta := 0.0
		if result == "fail" {
			delta = xccdfDelta(severity)
		}

		failAt := scanTime.Unix()
		if rr.Time != "" {
			if t, err := time.Parse(time.RFC3339, rr.Time); err == nil {
				failAt = t.Unix()
			}
		}

		checkID := sanitizeID(rr.ID)
		if checkID == "" {
			checkID = fmt.Sprintf("oscap-%s", rr.ID)
		}

		report.Items = append(report.Items, ExternalCheckResult{
			CheckID:  checkID,
			RuleID:  rr.ID,
			Title:   rr.ID,
			Result:  result,
			Severity: severity,
			Delta:   delta,
			FailAt:  failAt,
			Category: "XCCDF",
			Refs:    []string{tr.Benchmark},
		})

		totalScore += delta
		count++
	}

	if count > 0 {
		avgDelta := totalScore / count
		report.RawScore = 100.0 + avgDelta
		if report.RawScore < 0 {
			report.RawScore = 0
		}
	}

	return report, nil
}

// parseOVAL parses OVAL 5.11 results generated by `oscap oval eval --results FILE`.
func (a *openscapAdapter) parseOVAL(input []byte) (*ExternalAssessmentReport, error) {
	var results ovalResults
	if err := xml.Unmarshal(input, &results); err != nil {
		return nil, fmt.Errorf("openscap OVAL parse error: %w", err)
	}

	scanTime := time.Now()

	report := &ExternalAssessmentReport{
		Tool:     "openscap-oval",
		HostID:   "unknown",
		Hostname: "unknown",
		ScanTime: scanTime,
		Items:    make([]ExternalCheckResult, 0),
		Metadata: map[string]string{
			"generator": results.Generator.ProductName,
			"version":   results.Generator.Version,
		},
	}

	for _, cfg := range results.TestResult.TestedConfigs {
		report.HostID = cfg.ObjID
		break
	}

	var failCount, totalCount int
	for _, def := range results.TestResult.Definitions {
		result := normalizeOVALResult(def.Result)
		totalCount++

		delta := 0.0
		if result == "fail" {
			delta = xccdfDelta("medium")
			failCount++
		}

		report.Items = append(report.Items, ExternalCheckResult{
			CheckID:  sanitizeID(def.ID),
			RuleID:  def.ID,
			Title:   def.ID,
			Result:  result,
			Severity: "medium",
			Delta:   delta,
			FailAt:  scanTime.Unix(),
			Category: "OVAL",
		})
	}

	if totalCount > 0 {
		report.RawScore = 100.0 * float64(totalCount-failCount) / float64(totalCount)
	}

	return report, nil
}

func normalizeXCCDFResult(r string) string {
	switch r {
	case "pass", "fixed", "notselected", "notapplicable":
		return "pass"
	case "fail", "error", "unknown":
		return "fail"
	default:
		if strings.Contains(r, "pass") {
			return "pass"
		}
		return "fail"
	}
}

func normalizeOVALResult(r string) string {
	switch r {
	case "true", "error":
		return "fail"
	case "false", "not evaluated", "not applicable":
		return "pass"
	default:
		return "fail"
	}
}

func mapOpenSCAPSeverity(level string) string {
	switch level {
	case "fatal", "error":
		return "critical"
	case "warning":
		return "medium"
	case "info":
		return "info"
	default:
		return "unknown"
	}
}

// xccdfDelta maps XCCDF/DISA severity to SSAM delta.
// Follows DISA STIG categorization: Cat I=critical, Cat II=high, Cat III=medium, Cat IV=low.
func xccdfDelta(severity string) float64 {
	switch severity {
	case "critical", "high":
		return -10.0
	case "medium", "warning":
		return -7.5
	case "low", "minimal":
		return -5.0
	case "info", "informational":
		return 0.0
	default:
		return -5.0
	}
}

func sanitizeID(id string) string {
	id = strings.TrimPrefix(id, "xccdf_org.ssgproject.content_rule_")
	id = strings.TrimPrefix(id, "xccdf_mil.disa.stig_rule_")
	id = strings.TrimPrefix(id, "oval:")
	if id == "" {
		return id
	}
	return id
}
